[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]
confidence-threshold = 1.0

[bans]
wildcards = "deny"
highlight = "all"
