all-features = true

[advisories]
yanked = "deny"
notice = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
]
copyleft = "deny"
confidence-threshold = 1.0

[bans]
wildcards = "deny"
highlight = "all"
