all-features = true
[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "deny"

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
]
copyleft = "deny"
default = "deny"
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
