on:
  push:
    branches: [main]
  pull_request:

name: Continuous integration

env:
  # renovate: datasource=rust-version depName=rust
  RUST_NIGHTLY_VERSION: nightly-2026-08-20

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: ${{ env.RUST_NIGHTLY_VERSION }}
      - run: cargo fmt --all --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ env.RUST_NIGHTLY_VERSION }}
      - run: cargo clippy --all-features --all-targets -- -D warnings

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --rust-version --no-dev-deps

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --no-deps

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: EmbarkStudios/cargo-deny-action@v2

  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          components: llvm-tools-preview
          toolchain: ${{ env.RUST_NIGHTLY_VERSION }}
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --all-features --doctests --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          fail_ci_if_error: true
          use_oidc: true
